worker_processes auto;

events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    client_max_body_size 64m;

    server {
        listen 80;
        server_name $DOMAIN www.$DOMAIN;
        return 301 https://$host:8443$request_uri;
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name www.$DOMAIN $DOMAIN;

        ssl_certificate     /etc/nginx/certs/$DOMAIN.crt;
        ssl_certificate_key /etc/nginx/certs/$DOMAIN.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        root  /var/www/wordpress;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~* \.(css|js|jpg|jpeg|gif|png|svg|ico|webp)$ {
            add_header Cache-Control "public, max-age=31536000, immutable";
            try_files $uri =404;
        }

        location ^~ /auth/ {
        proxy_pass         http://keycloak:8080/auth/;
        proxy_http_version 1.1;
        proxy_set_header   Host $http_host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_set_header   X-Forwarded-Port 8443;
        proxy_set_header   X-Forwarded-Host $http_host;
        proxy_set_header   X-Forwarded-Prefix /auth;
        proxy_set_header   Connection ""; 
        }

        
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;

            fastcgi_param HTTP_HOST $http_host;
            fastcgi_param HTTPS on;
            fastcgi_param SERVER_PORT 8443;

            fastcgi_param HTTP_X_FORWARDED_PROTO https;
            fastcgi_param HTTP_X_FORWARDED_SSL on;
            fastcgi_param HTTP_X_FORWARDED_PORT 8443;

            fastcgi_pass wordpress:9000;
        }
    }
}

